### ISSUE TITLE
Graceful shutdown of workers during kubernetes deploy

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1062]
If a deploy happens during a job, it will just be left hanging when the worker is killed. Instead, kubernetes should send a signal to the worker requesting a warm shut down, and the worker can exit gracefully after its current job.

**Comment by Sumukh** [comment]
Adding this to the spec with a grace period should do the trick 
```
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["rq","suspend"]
```
Source: https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html
